base_model_name: best_yolov8_model.pt
batch_size: 4
datasets_dir: datasets
device: cpu
epochs: 5
fliplr: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
img_size: 480
iou: 0.7
learning_rate: 0.005479254982464243
mosaic: 1.0
optimizer: AdamW
output_model_name: retrained_yolov8_model.pt
patience: 100
saved_models_dir: saved_models
scale: 0.5
val: true
workers: 8
